export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ERROR_OCCURED = 'ERROR_OCCURED';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

export const FETCH_POSTS = 'FETCH_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_LIKES = 'GET_LIKES';
export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = 'REMOVE_LIKE';
