export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ERROR_HAS_OCCURED = 'ERROR_HAS_OCCURED';

export const REMOVE_EXP = 'REMOVE_EXP';
